name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run tests and generate report
        run: |
          # Запуск тестов и сохранение вывода в файл
          python -m unittest discover -s tests -v > test-output.log 2>&1 || true

          # Создание Markdown-отчёта
          echo "# Test Results" > report.md
          echo "## Test Output" >> report.md
          echo '```' >> report.md
          cat test-output.log >> report.md
          echo '```' >> report.md

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.md

    needs: build  

  publish:
    runs-on: ubuntu-latest  
    needs: test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./report

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          keep_files: false
