name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Если у вас есть файл requirements.txt

  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Запускаем unittests из директории tests
    
    needs: build  
