name: CI

on:
  workflow_dispatch:  # Запуск вручную через интерфейс GitHub

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v 2>&1 | tee tests/result.log

      - name: Check result.log content
        run: cat tests/result.log

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/result.log

    needs: build  

  artifacts:
    runs-on: ubuntu-latest  
    needs: test  

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: tests/

      - name: List files
        run: ls -la tests

      - name: Upload test results with unique name
        uses: actions/upload-artifact@v4
        with:
          name: test-results-final-${{ github.run_id }}
          path: tests/result.log
