name: CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          python -m unittest discover -s tests -v > result.log || true  # Сохраняем вывод в файл

    needs: build  

  artifacts:
    runs-on: ubuntu-latest  
    needs: test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test-results
          path: result.log  
